### ISSUE TITLE
为何在清新美女选择一个图看大图是黑屏（而校园就是好的）

### ISSUE THREAD

**Issue by tommycom-sudo** [kunkun12/Flutter_shop#4]
为何在清新美女选择一个图看大图是黑屏（而校园就是好的）

（环境是模拟器上运行的）

**Comment by tommycom-sudo** [comment]
补充：古装，动漫也是点击看大图是黑屏，而壁纸也是好的

**Comment by kunkun12** [comment]
> 补充：古装，动漫也是点击看大图是黑屏，而壁纸也是好的

刚才我在本地模拟器上试了一下iOS模拟器 展示是正常的。编译为android的APK在android真机上也没问题

**Comment by tommycom-sudo** [comment]
谢谢您的代码写的太牛了！！收获很多
